name: stellar_anchor_library
description: Anchor Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  responsive_builder: 0.1.7
  shared_preferences: ^0.5.10
  firebase_auth:
  firebase_messaging:
  cloud_firestore:
  firebase_storage: ^4.0.0
  firebase_core : ^0.5.0
  intl: ^0.16.1
  http:
  uuid: ^2.2.0
  flutter_dotenv: ^2.1.0
  animations: 1.0.0+5
  page_transition: ^1.1.6
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  stellarplugin: ^0.0.3+12
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.7+6
  mobmongo: ^0.0.8+1
  contacts_service: ^0.4.6
  mime_type: ^0.3.2
  qrscan: ^0.2.17
  circular_profile_avatar: ^1.0.6
  autocomplete_textfield: ^1.7.3
  permission_handler: ^5.0.1+1
  qr_flutter:
  dots_indicator: ^1.2.0
  camera: ^0.5.8+5
  file_picker: ^1.13.3
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.5.0
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  


