name: stellar_anchor_library
description: Anchor Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  responsive_builder: 0.1.5
  shared_preferences: 0.5.7
  firebase_auth: 0.16.0
  firebase_messaging: 6.0.13
  cloud_firestore: ^0.13.5
  intl: ^0.16.1
  http:
  uuid: ^2.0.4
  flutter_dotenv: ^2.1.0
  animations: 1.0.0+5
  page_transition: ^1.1.5
  google_fonts: ^1.0.0
  cached_network_image: ^2.1.0+1
  #  service_worker: 0.2.4
  #  cloud_firestore: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


