name: stellar_anchor_library
description: Anchor Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  responsive_builder: 0.1.5
  shared_preferences: ^0.5.7
  firebase_auth: 0.16.0
  firebase_messaging: 6.0.13
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  intl: ^0.16.1
  http:
  uuid: ^2.0.4
  flutter_dotenv: ^2.1.0
  animations: 1.0.0+5
  page_transition: ^1.1.5
  google_fonts: ^1.0.0
  cached_network_image: ^2.1.0+1
  stellarplugin: ^0.0.3+12
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.5+3
  mobmongo: ^0.0.8+1
  contacts_service: ^0.4.4
  mime_type: ^0.3.0
  qrscan: ^0.2.17
  circular_profile_avatar: ^1.0.6
  autocomplete_textfield: ^1.7.3
  permission_handler: ^5.0.0+hotfix.4
  qr_flutter:
  dots_indicator: ^1.1.0
  camera: ^0.5.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  


